import { useState } from 'react';

const snippets = {
  container: `.responsive-demo { container-type: inline-size; }\n.responsive-card { display: flex; }\n@container (max-width: 320px) {\n  .responsive-card { flex-direction: column; }\n}`,
  subgrid: `.aligned-grid {\n  display: grid;\n  grid-template-columns: repeat(2, 1fr);\n}\n.aligned-card {\n  display: grid; grid-row: span 3;\n  grid-template-rows: subgrid;\n}`,
  snap: `.snap-track {\n  display: flex; overflow-x: auto;\n  scroll-snap-type: x mandatory;\n}\n.snap-slide {\n  flex: 0 0 85%; scroll-snap-align: center;\n}`,
  state: `const [quantity, setQuantity] = useState(1);\nconst total = quantity * 24000;\n<button onClick={() => setQuantity(q => q + 1)}>\n  +\n</button>\n<output>{total.toLocaleString()}원</output>`,
  transform: `const [angle, setAngle] = useState(25);\n<div style={{\n  transform: \`rotateX(-20deg) rotateY(\${angle}deg)\`\n}} />\n<input type="range" value={angle}\n  onChange={e => setAngle(Number(e.target.value))} />`,
};

function Demo({ number, title, tech, description, code, children }: { number: string; title: string; tech: string; description: string; code: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const [applied, setApplied] = useState(true);
  const comparisonNotes: Record<string, string> = {
    "01": "슬라이더를 왼쪽으로 움직여 카드가 들어가는 공간을 좁혀 보세요.\n적용 전: 공간이 좁아져도 그림과 글이 계속 옆으로 놓여 글이 비좁아집니다.\n적용 후: 공간이 320px 이하가 되면 그림이 위로, 글이 아래로 배치됩니다. 브라우저 창 크기가 아니라 카드가 들어간 공간의 너비에 반응합니다.",
    "02": "‘긴 제목 적용’을 켠 상태에서 두 카드의 설명과 하단 링크 높이를 비교해 보세요.\n적용 전: 각 카드가 따로 배치되어 긴 제목 아래의 설명과 링크가 더 아래로 밀립니다.\n적용 후: 두 카드가 같은 행 기준을 공유해 제목 길이가 달라도 설명과 하단 링크가 나란히 정렬됩니다.",
    "03": "갤러리 위에서 가로로 스크롤한 뒤 손을 떼 보세요. 휴대폰에서는 좌우로 밀고, 트랙패드에서는 두 손가락으로 좌우 스크롤할 수 있습니다.\n적용 전: 손을 뗀 위치에 그대로 멈춰 카드가 반쯤 보일 수 있습니다.\n적용 후: 가까운 카드가 가운데에 오도록 스크롤 위치가 자동으로 조정됩니다. 처음과 마지막 카드는 스크롤 범위의 끝에 맞춰집니다. 화살표 버튼으로도 차이를 확인할 수 있습니다.",
    "04": "‘+’ 버튼을 눌러 수량을 2개로 늘린 뒤 합계를 비교해 보세요.\n적용 전: 합계를 24,000원으로 고정해 둔 예시라 수량만 바뀌고 가격은 그대로입니다.\n적용 후: 수량 × 개당 가격으로 합계를 계산해 2개면 48,000원, 3개면 72,000원이 표시됩니다. 이 차이는 React만의 기능이 아니라 화면의 값을 상태에 연결했는지의 차이입니다.",
    "05": "회전 각도 슬라이더를 움직이며 같은 오브젝트를 비교해 보세요.\n적용 전: 입체 효과와 회전을 꺼 두어 정면의 평평한 사각형만 보입니다. 슬라이더 값이 바뀌어도 모양은 회전하지 않습니다.\n적용 후: 여러 면으로 구성된 큐브가 선택한 각도로 회전합니다. 원근 효과 덕분에 앞뒤의 깊이도 느껴집니다. 토글을 바꿔도 선택한 각도는 유지됩니다.",
  };
  return <article className="tech-demo"><div className="demo-title"><span>{number} / {tech}</span><span className="live-dot">LIVE DEMO</span></div><h3>{title}</h3><p className="demo-description">{description}</p><div className="comparison-toggle" role="group" aria-label={`${title} 적용 비교`}><button aria-pressed={!applied} onClick={() => setApplied(false)}>적용 전</button><button aria-pressed={applied} onClick={() => setApplied(true)}>적용 후</button></div><p className="comparison-note">{comparisonNotes[number]}</p><div className={`demo-stage ${applied ? "tech-applied" : "tech-before"}`}>{children}</div><button className="code-toggle" aria-expanded={open} onClick={() => setOpen(!open)}><span>{'</>'} 적용된 핵심 코드</span><span>{open ? '접기 −' : '펼치기 +'}</span></button>{open && <pre className="demo-code"><code>{code}</code></pre>}</article>;
}

export default function TechDemos() {
  const [width, setWidth] = useState(100);
  const [longTitle, setLongTitle] = useState(true);
  const [quantity, setQuantity] = useState(1);
  const [angle, setAngle] = useState(25);
  return <div className="tech-demo-grid">
    <Demo number="01" title="화면 대신, 공간에 반응하는 카드" tech="CSS / CONTAINER QUERIES" description="너비를 줄여 보세요. 카드가 놓인 공간이 320px 이하가 되면 세로 배치로 바뀝니다." code={snippets.container}><div className="demo-controls"><label htmlFor="container-width">컨테이너 너비</label><input id="container-width" type="range" min="55" max="100" value={width} onChange={e => setWidth(Number(e.target.value))}/><output>{width}%</output></div><div className="responsive-demo" style={{ width: `${width}%` }}><div className="responsive-card"><div className="responsive-art">✳</div><div><small>DESIGN NOTE / 001</small><h4>작은 공간의 가능성</h4><p>어디에 놓여도 자연스럽게.<br/>컴포넌트의 크기로 결정되는 레이아웃.</p><span>Read story ↗</span></div></div></div></Demo>
    <Demo number="02" title="다른 내용, 같은 정렬선" tech="CSS / SUBGRID" description="제목 길이를 바꿔도 설명과 버튼은 같은 줄에 맞춰집니다. 부모 그리드의 행을 공유합니다." code={snippets.subgrid}><div className="demo-controls"><label htmlFor="long-title">긴 제목 적용</label><input id="long-title" type="checkbox" checked={longTitle} onChange={e => setLongTitle(e.target.checked)}/></div><div className="aligned-grid"><div className="aligned-card"><h4>{longTitle ? '일상의 작은 순간을 발견하는 새로운 디자인 이야기' : '디자인 이야기'}</h4><p>긴 제목이 있어도 카드의 정보는 같은 기준선에 놓입니다.</p><span>Explore ↗</span></div><div className="aligned-card"><h4>Build something.</h4><p>짧은 제목 아래에도 같은 정렬을 유지합니다.</p><span>Explore ↗</span></div></div></Demo>
    <Demo number="03" title="손끝에서 멈추는 갤러리" tech="CSS / SCROLL SNAP" description="좌우로 스크롤하거나 버튼을 눌러 보세요. 스크롤이 끝나면 카드가 중앙에 맞춰집니다." code={snippets.snap}><div className="demo-controls"><span>가로 스크롤로 탐색</span><div className="snap-buttons"><button aria-label="이전 카드" onClick={e => e.currentTarget.closest('.demo-stage')?.querySelector('.snap-track')?.scrollBy({ left: -300, behavior: 'smooth' })}>←</button><button aria-label="다음 카드" onClick={e => e.currentTarget.closest('.demo-stage')?.querySelector('.snap-track')?.scrollBy({ left: 300, behavior: 'smooth' })}>→</button></div></div><div className="snap-track" tabIndex={0} aria-label="가로 스크롤 갤러리">{['FORM', 'COLOR', 'SPACE'].map((word, i) => <div className={`snap-slide slide-${i}`} key={word}><span>0{i + 1} / VISUAL STUDY</span><strong>{word}</strong><span>{['◇', '◉', '▦'][i]}</span></div>)}</div></Demo>
    <Demo number="04" title="하나의 상태, 바로 바뀌는 화면" tech="REACT / STATE" description="수량을 조절하면 합계가 즉시 갱신됩니다. 화면에 표시되는 값은 같은 상태에서 계산합니다." code={snippets.state}><div className="state-product"><div className="product-symbol">◒</div><div><small>EVERYDAY OBJECTS</small><h4>Everyday cup</h4><span>24,000원 / 개</span></div></div><div className="quantity-controls"><span>수량</span><div><button aria-label="수량 줄이기" disabled={quantity === 1} onClick={() => setQuantity(q => Math.max(1, q - 1))}>−</button><output aria-live="polite">{quantity}</output><button aria-label="수량 늘리기" onClick={() => setQuantity(q => q + 1)}>+</button></div></div><div className="state-total"><span>합계</span><output className="calculated-total" aria-live="polite">{(quantity * 24000).toLocaleString()}원</output><span className="fixed-total">24,000원 <small>고정된 합계</small></span></div></Demo>
    <Demo number="05" title="CSS로 만드는 작은 3D 공간" tech="CSS + REACT / 3D TRANSFORMS" description="슬라이더로 회전 각도를 조절하세요. CSS 원근과 3D 변환을 React 상태에 연결했습니다." code={snippets.transform}><div className="cube-perspective"><div className="css-cube" style={{ transform: `rotateX(-20deg) rotateY(${angle}deg)` }}>{['front','back','left','right','top','bottom'].map(face => <div className={`cube-face ${face}`} key={face}>✳</div>)}</div></div><div className="demo-controls"><label htmlFor="cube-angle">회전 각도</label><input id="cube-angle" type="range" min="0" max="360" value={angle} onChange={e => setAngle(Number(e.target.value))}/><output>{angle}°</output></div></Demo>
    <aside className="demo-invitation"><span className="eyebrow">SMALL EXPERIMENTS. REAL POSSIBILITIES.</span><span className="invitation-symbol">✳</span><h3>한 가지 기술을,<br/>확실히 이해하는 방법.</h3><p>직접 바꾸고, 결과를 보고, 코드를 살펴보세요.<br/>작은 데모가 실제 화면을 만드는 재료가 됩니다.</p><a href="#playground">WebGL 3D 실험도 살펴보기 ↗</a></aside>
  </div>;
}
